apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: nexora
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: kafka:29092
    - name: authType
      value: none
    - name: consumeRetryInterval
      value: "200ms"
