apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore-vault
  namespace: nexora
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
    - name: vaultAddr
      value: "http://vault:8200"
    - name: vaultToken
      value: "nexora-dev-token"
    - name: vaultKVPrefix
      value: "nexora"
    - name: vaultKVUsePrefix
      value: "true"
    - name: enginePath
      value: "secret"
